# aqui tenho que colocar o nome do pipeline(fluxo de trabalho - workflow)
name: Primeiro Woverflow
# em quais gatilho quero que dispare meu script
on:
  push:
    branches:
      - developer
      - main
      - master
  pull_request:
    branches: [main, master]
# quais sao os trabaçhos (fluxos) a serem executados pelo workflow
jobs:
  Primeiro-fluxo:
# este é o nome do fluxo de trabalho
  name: Job1 
# para ser executado nesta maquina virual
  runs-on: ubuntu-latest
# agora irei incluir os passos do script
steps:
  - name: Passo 1
    run: echo "Executando o primeiro passo."
  - name: Passo 2
    run: echo "Executando o segundo passo."
  - name: Passo 3"
    run: echo "Executando o terceiro passo."
  
jobs2:
  Segundo-fluxo:
# este é o nome do fluxo de trabalho
  name: Job2
# para ser executado nesta maquina virual
  runs-on: ubuntu-latest
# agora irei incluir os passos do script
  steps:
    - name: Passo 4
      run: echo "Executando o primeiro passo."
    - name: Passo 5
      run: echo "Executando o segundo passo."
    - name: Passo 6
      run: echo "Executando o terceiro passo."
  
jobs3:
  Terceiro-fluxo:
# este é o nome do fluxo de trabalho
  name: Job3
# para ser executado nesta maquina virual
  runs-on: ubuntu-latest
# agora irei incluir os passos do script
  steps:
    - name: Passo 7
      run: echo "Executando o primeiro passo."
    - name: Passo 8
      run: echo "Executando o segundo passo."
    - name: Passo 9"
      run: echo "Executando o terceiro passo."
